<?xml version='1.1' encoding='UTF-8'?>
<flow-build plugin="workflow-job@1476.v90f02a_225559">
  <actions>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.model.Cause_-UserIdCause>
            <userId>balu</userId>
          </hudson.model.Cause_-UserIdCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
    <jenkins.metrics.impl.TimeInQueueAction plugin="metrics@4.2.21-458.vcf496cb_839e4">
      <queuingDurationMillis>21</queuingDurationMillis>
      <blockedDurationMillis>0</blockedDurationMillis>
      <buildableDurationMillis>0</buildableDurationMillis>
      <waitingDurationMillis>7</waitingDurationMillis>
    </jenkins.metrics.impl.TimeInQueueAction>
  </actions>
  <queueId>1</queueId>
  <timestamp>1736767721909</timestamp>
  <startTime>1736767721920</startTime>
  <result>FAILURE</result>
  <duration>69</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <completed>true</completed>
  <checkouts class="hudson.util.PersistedList">
    <org.jenkinsci.plugins.workflow.job.WorkflowRun_-SCMCheckout>
      <scm class="hudson.scm.NullSCM"/>
      <node></node>
      <workspace>/var/lib/jenkins/workspace/job1@script/977219c24af05382b61aa0628b08423fcc960a2b0017abf95a20cc94af766cb5</workspace>
      <changelogFile>/var/lib/jenkins/jobs/job1/builds/1/changelog4318698188098294244.xml</changelogFile>
    </org.jenkinsci.plugins.workflow.job.WorkflowRun_-SCMCheckout>
  </checkouts>
</flow-build>